// Base64 encoded images for math questions
// These images are embedded directly in the application to ensure they load consistently

export const images = {
  // Basic shapes
  circle: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48Y2lyY2xlIGN4PSI1MCIgY3k9IjUwIiByPSI0MCIgZmlsbD0iIzMzOThkYiIgLz48L3N2Zz4=",
  square: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB4PSIxMCIgeT0iMTAiIHdpZHRoPSI4MCIgaGVpZ2h0PSI4MCIgZmlsbD0iI2UyNGMzYiIgLz48L3N2Zz4=",
  triangle: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cG9seWdvbiBwb2ludHM9IjUwLDEwIDkwLDkwIDEwLDkwIiBmaWxsPSIjMmVjYzcxIiAvPjwvc3ZnPg==",
  rectangle: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB4PSIxMCIgeT0iMzAiIHdpZHRoPSI4MCIgaGVpZ2h0PSI0MCIgZmlsbD0iI2Y5OWYwMCIgLz48L3N2Zz4=",
  star: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNNTAgMTBMNjEgMzVINjhMODggMjVMNjQgNDVINzkuMDlMOTAgNjVMNzEgNDJMNzUgNjVMNjUgNzlMNTAgNjBMMzUgNzlMMjUgNjVMMjkgNDJMMTAgNjVMMjAuOTEgNDVIMzZMMTIgMjVMMzIgMzVIMzlMNTAgMTBaIiBmaWxsPSIjZjFjNDBmIiAvPjwvc3ZnPg==",
  
  // Multi-shape collections
  shapes: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzAwIiBoZWlnaHQ9IjIwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSJ3aGl0ZSIvPjxjaXJjbGUgY3g9IjUwIiBjeT0iNTAiIHI9IjMwIiBmaWxsPSIjMzM5OGRiIiAvPjxyZWN0IHg9IjExMCIgeT0iMjAiIHdpZHRoPSI2MCIgaGVpZ2h0PSI2MCIgZmlsbD0iI2UyNGMzYiIgLz48cG9seWdvbiBwb2ludHM9IjI1MCw1MCAyODAsOTAgMjIwLDkwIiBmaWxsPSIjMmVjYzcxIiAvPjwvc3ZnPg==",
  
  // Counting objects
  threeCircles: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzAwIiBoZWlnaHQ9IjIwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSJ3aGl0ZSIvPjxjaXJjbGUgY3g9IjYwIiBjeT0iODAiIHI9IjIwIiBmaWxsPSIjMzM5OGRiIiAvPjxjaXJjbGUgY3g9IjE1MCIgY3k9IjgwIiByPSIyMCIgZmlsbD0iIzMzOThkYiIgLz48Y2lyY2xlIGN4PSIyNDAiIGN5PSI4MCIgcj0iMjAiIGZpbGw9IiMzMzk4ZGIiIC8+PC9zdmc+",
  fiveStars: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzAwIiBoZWlnaHQ9IjIwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSJ3aGl0ZSIvPjxwYXRoIGQ9Ik01MCAzMEw1OCA0NUg3NEw2MSA1NUw2NiA3MEw1MCA2MEwzNCA3MEwzOSA1NUwyNiA0NUg0Mkw1MCAzMFoiIGZpbGw9IiNmMWM0MGYiIC8+PHBhdGggZD0iTTEwMCAzMEwxMDggNDVIMTI0TDExMSA1NUwxMTYgNzBMMTAwIDYwTDg0IDcwTDg5IDU1TDc2IDQ1SDkyTDEwMCAzMFoiIGZpbGw9IiNmMWM0MGYiIC8+PHBhdGggZD0iTTE1MCAzMEwxNTggNDVIMTc0TDE2MSA1NUwxNjYgNzBMMTUwIDYwTDEzNCA3MEwxMzkgNTVMMTI2IDQ1SDE0MkwxNTAgMzBaIiBmaWxsPSIjZjFjNDBmIiAvPjxwYXRoIGQ9Ik0yMDAgMzBMMjA4IDQ1SDIyNEwyMTEgNTVMMjE2IDcwTDIwMCA2MEwxODQgNzBMMTg5IDU1TDE3NiA0NUgxOTJMMjAwIDMwWiIgZmlsbD0iI2YxYzQwZiIgLz48cGF0aCBkPSJNMjUwIDMwTDI1OCA0NUgyNzRMMjYxIDU1TDI2NiA3MEwyNTAgNjBMMjM0IDcwTDIzOSA1NUwyMjYgNDVIMjQyTDI1MCAzMFoiIGZpbGw9IiNmMWM0MGYiIC8+PC9zdmc+",
  fourSquares: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzAwIiBoZWlnaHQ9IjIwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSJ3aGl0ZSIvPjxyZWN0IHg9IjMwIiB5PSIzMCIgd2lkdGg9IjQwIiBoZWlnaHQ9IjQwIiBmaWxsPSIjZTI0YzNiIiAvPjxyZWN0IHg9IjEwMCIgeT0iMzAiIHdpZHRoPSI0MCIgaGVpZ2h0PSI0MCIgZmlsbD0iI2UyNGMzYiIgLz48cmVjdCB4PSIxNzAiIHk9IjMwIiB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIGZpbGw9IiNlMjRjM2IiIC8+PHJlY3QgeD0iMjQwIiB5PSIzMCIgd2lkdGg9IjQwIiBoZWlnaHQ9IjQwIiBmaWxsPSIjZTI0YzNiIiAvPjwvc3ZnPg==",
  twoTriangles: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzAwIiBoZWlnaHQ9IjIwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSJ3aGl0ZSIvPjxwb2x5Z29uIHBvaW50cz0iODAsNDAgMTIwLDExMCA0MCwxMTAiIGZpbGw9IiMyZWNjNzEiIC8+PHBvbHlnb24gcG9pbnRzPSIyMjAsNDAgMjYwLDExMCAxODAsMTEwIiBmaWxsPSIjMmVjYzcxIiAvPjwvc3ZnPg==",
  
  // Multi-colored shapes
  coloredShapes: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzAwIiBoZWlnaHQ9IjIwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSJ3aGl0ZSIvPjxjaXJjbGUgY3g9IjYwIiBjeT0iNTAiIHI9IjIwIiBmaWxsPSIjRkY1NzMzIiAvPjxjaXJjbGUgY3g9IjEyMCIgY3k9IjUwIiByPSIyMCIgZmlsbD0iIzM0OThEQiIgLz48Y2lyY2xlIGN4PSIxODAiIGN5PSI1MCIgcj0iMjAiIGZpbGw9IiNGMUM0MEYiIC8+PHBvbHlnb24gcG9pbnRzPSI2MCwxMjAgMTAwLDE2MCAyMCwxNjAiIGZpbGw9IiMyRUNDNzEiIC8+PHJlY3QgeD0iMTE1IiB5PSIxMTUiIHdpZHRoPSI0MCIgaGVpZ2h0PSI0MCIgZmlsbD0iIzlCNTlCNiIgLz48cmVjdCB4PSIxODAiIHk9IjExNSIgd2lkdGg9IjQwIiBoZWlnaHQ9IjIwIiBmaWxsPSIjRkY5NTAwIiAvPjwvc3ZnPg==",
  fractionHalf: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzAwIiBoZWlnaHQ9IjIwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSJ3aGl0ZSIvPjxyZWN0IHg9IjMwIiB5PSI4MCIgd2lkdGg9IjI0MCIgaGVpZ2h0PSI0MCIgZmlsbD0ibm9uZSIgc3Ryb2tlPSJibGFjayIgc3Ryb2tlLXdpZHRoPSIyIiAvPjxsaW5lIHgxPSIxNTAiIHkxPSI4MCIgeDI9IjE1MCIgeTI9IjEyMCIgc3Ryb2tlPSJibGFjayIgc3Ryb2tlLXdpZHRoPSIyIiAvPjxyZWN0IHg9IjMwIiB5PSI4MCIgd2lkdGg9IjEyMCIgaGVpZ2h0PSI0MCIgZmlsbD0iI0ZGRDcwMCIgLz48L3N2Zz4=",
  
  // Different counts of objects
  oneObject: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzAwIiBoZWlnaHQ9IjIwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSJ3aGl0ZSIvPjxjaXJjbGUgY3g9IjE1MCIgY3k9IjgwIiByPSIzMCIgZmlsbD0iIzMzOThkYiIgLz48L3N2Zz4=",
  twoObjects: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzAwIiBoZWlnaHQ9IjIwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSJ3aGl0ZSIvPjxjaXJjbGUgY3g9IjEwMCIgY3k9IjgwIiByPSIzMCIgZmlsbD0iIzMzOThkYiIgLz48Y2lyY2xlIGN4PSIyMDAiIGN5PSI4MCIgcj0iMzAiIGZpbGw9IiMzMzk4ZGIiIC8+PC9zdmc+",
  threeObjects: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzAwIiBoZWlnaHQ9IjIwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSJ3aGl0ZSIvPjxjaXJjbGUgY3g9IjYwIiBjeT0iODAiIHI9IjIwIiBmaWxsPSIjMzM5OGRiIiAvPjxjaXJjbGUgY3g9IjE1MCIgY3k9IjgwIiByPSIyMCIgZmlsbD0iIzMzOThkYiIgLz48Y2lyY2xlIGN4PSIyNDAiIGN5PSI4MCIgcj0iMjAiIGZpbGw9IiMzMzk4ZGIiIC8+PC9zdmc+",
  fourObjects: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzAwIiBoZWlnaHQ9IjIwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSJ3aGl0ZSIvPjxjaXJjbGUgY3g9IjUwIiBjeT0iNTAiIHI9IjIwIiBmaWxsPSIjMzM5OGRiIiAvPjxjaXJjbGUgY3g9IjE1MCIgY3k9IjUwIiByPSIyMCIgZmlsbD0iIzMzOThkYiIgLz48Y2lyY2xlIGN4PSI1MCIgY3k9IjEyMCIgcj0iMjAiIGZpbGw9IiMzMzk4ZGIiIC8+PGNpcmNsZSBjeD0iMTUwIiBjeT0iMTIwIiByPSIyMCIgZmlsbD0iIzMzOThkYiIgLz48L3N2Zz4=",
  fiveObjects: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzAwIiBoZWlnaHQ9IjIwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSJ3aGl0ZSIvPjxjaXJjbGUgY3g9IjUwIiBjeT0iNTAiIHI9IjIwIiBmaWxsPSIjMzM5OGRiIiAvPjxjaXJjbGUgY3g9IjE1MCIgY3k9IjUwIiByPSIyMCIgZmlsbD0iIzMzOThkYiIgLz48Y2lyY2xlIGN4PSIyNTAiIGN5PSI1MCIgcj0iMjAiIGZpbGw9IiMzMzk4ZGIiIC8+PGNpcmNsZSBjeD0iMTAwIiBjeT0iMTIwIiByPSIyMCIgZmlsbD0iIzMzOThkYiIgLz48Y2lyY2xlIGN4PSIyMDAiIGN5PSIxMjAiIHI9IjIwIiBmaWxsPSIjMzM5OGRiIiAvPjwvc3ZnPg=="
};

// Arrays of counting images for different counts
export const countingImages = {
  1: images.oneObject,
  2: images.twoObjects,
  3: images.threeObjects,
  4: images.fourObjects,
  5: images.fiveObjects
};

// Get an image for a specific number of shapes
export const getCountingImage = (count: number, shape = 'circle'): string => {
  if (count === 1) return images.oneObject;
  if (count === 2) return shape === 'triangle' ? images.twoTriangles : images.twoObjects;
  if (count === 3) return shape === 'circle' ? images.threeCircles : images.threeObjects;
  if (count === 4) return shape === 'square' ? images.fourSquares : images.fourObjects;
  if (count === 5) return shape === 'star' ? images.fiveStars : images.fiveObjects;
  
  // Fallback to default counting image
  return images.coloredShapes;
};

// Get an image for a specific shape
export const getShapeImage = (shape: string): string => {
  const shapeName = shape.toLowerCase();
  if (shapeName.includes('circle')) return images.circle;
  if (shapeName.includes('square')) return images.square;
  if (shapeName.includes('triangle')) return images.triangle;
  if (shapeName.includes('rectangle')) return images.rectangle;
  if (shapeName.includes('star')) return images.star;
  
  // Fallback to the shapes collection
  return images.shapes;
};

// Get an image for a fraction
export const getFractionImage = (numerator: number, denominator: number): string => {
  // For now just return the half image as an example
  if (numerator === 1 && denominator === 2) return images.fractionHalf;
  
  // For other fractions, we'd ideally have specific images
  return images.fractionHalf; // Fallback
};