-- COMPLETED MIGRATION: Standardized all users' hidden_grade_asset structure to match user 14
-- Successfully migrated 37 users to have consistent structure while preserving existing data
-- 
-- Migration completed on: 2025-06-21
-- Result: All 38 users now have standardized structure with:
-- - modules (14 modules with consistent keys and structure)  
-- - ai_analytics (analysis and learning patterns)
-- - global_stats (user statistics and progress tracking)
-- - concept_mastery (15 concepts with mastery tracking)
-- - cross_module_analytics (learning patterns between modules)
--
-- Existing user data was preserved where possible during the migration.